[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Map /api/* to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for client routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
